# 3.1 Error handling
Error handling is an essential function of our project and is up to us to deal with it. Neither is Objection.js or Knex.js handling any errors.

### Current state of error handling
We have seen in *Chapter 2.4 - Validation* that currently, we handle errors on a case level using a try/catch block. And honestly, we don't handle any errors here; we simply respond with the error message to the REST API.

Example: **/routes/api/users.js**
```js
// ...

// Create new user
router.post("/", async (req, res) => {
    const {name, age} = req.body;
    try {
        const user = await User.query().insert({ name, age }); 
        res.json(user);
    } catch (err) {
        res.status(400).json(err.data);
    }
});

// ...
```
The way we currently handle errors is not optimized for a larger project. 

**First of all**, how can we guarantee that we always use the same schema of returned errors?
By way of an example, for the users route, *developer A* responds with the full `err.data` object to the API (just like in our code above). 
However, for the todos route, developer B feels that the response needs additional details and wraps the data in an object, like below
```js
return res.status(400).json({status: "false", data: err.data});
```
Having no unified error response confuses the API user. There are no properties he/she can rely on to handle responses correctly.

**Second**, if you have a large project, how do you make sure that it runs properly and interfere when a significant error happen? 
You need a way to access errors that might be with logging each error in log files or using one of many monitoring products like [PM2](https://www.npmjs.com/package/pm2)  or [Sentry](https://sentry.io/welcome/). 
Right now, our project only displays the error to the API-user, and we have no way of accessing them.


**Finally**, handling errors and returning a response for every try/catch and if/else statement becomes very tedious and makes the codebase messy.


## Improved error handling
The solution is to move error handling to a distinct error handling function, and this applies for every Express.js project, not only with Knex.js and Objection.js. A unified and consistent error structure is guaranteed with a distinct function.

> **Note**
> But you should never send the errors directly to the client as they may contain SQL and other information that reveals too much about the inner workings of your app.

Objection.js provides a set of case-specific errors. 
Some are:
- `ValidationError` - thrown if validation of any input fails. By input, we mean any data that can come from the outside world, like model instances (using *jsonSchema()*). Returns an HTTP 400 - Bad Request
- `NotFoundError` - has to be invoked manually. Best suited during a get/find query when nothing was found, then you can do `throw new NotFoundError(emptyResult)` to invoke this error. Returns a HTTP 404 Not found
- `DBError` - thrown if the database client, in our case `mysql`, throws an error

Objection.js documentation page provides an [error handler function](https://vincit.github.io/objection.js/recipes/error-handling.html) specifically made for Objection.js. We are about to implement and use a better, slightly modified version of it in our project. 

We haven't used, nor created any helper functions yet (which error handlers are a part of). Therefore, we have to create a new folder called **/helpers** with the **error.js** file and import the following code

**/helpers/error.js**
```js
/**
 * Custom Objection.js error handler
 */

// Import all Error types
const {
  ValidationError,
  NotFoundError,
  DBError,
  ConstraintViolationError,
  UniqueViolationError,
  NotNullViolationError,
  ForeignKeyViolationError,
  CheckViolationError,
  DataError
} = require("objection");

// Our custom Error Handler
// err and res are arguments coming from Express.js
function errorHandler(err, res) {
  // Handle Error with type ValidationError -> User input data was false
  if (err instanceof ValidationError) {
    switch (err.type) {
      case "ModelValidation":
        res.status(400).send({
          message: err.message,
          type: err.type,
          data: err.data
        });
        break;
      case "RelationExpression":
        res.status(400).send({
          message: err.message,
          type: "RelationExpression",
          data: {}
        });
        break;
      case "UnallowedRelation":
        res.status(400).send({
          message: err.message,
          type: err.type,
          data: {}
        });
        break;
      case "InvalidGraph":
        res.status(400).send({
          message: err.message,
          type: err.type,
          data: {}
        });
        break;
      default:
        res.status(400).send({
          message: err.message,
          type: "UnknownValidationError",
          data: {}
        });
        break;
    }
  } else if (err instanceof NotFoundError) {
    // Handle Error with type NotFoundError -> manually invoked using "throw new NotFoundError"
    res.status(404).send({
      message: err.message,
      type: "NotFound",
      data: {}
    });
  } else if (err instanceof UniqueViolationError) {
    // Handle Error with type UniqueViolationError -> database threw a constraint error
    res.status(409).send({
      message: err.message,
      type: "UniqueViolation",
      data: {
        columns: err.columns,
        table: err.table,
        constraint: err.constraint
      }
    });
  } else if (err instanceof NotNullViolationError) {
    // Handle Error with type NotNullViolationError -> database threw a constraint error
    res.status(400).send({
      message: err.message,
      type: "NotNullViolation",
      data: {
        column: err.column,
        table: err.table
      }
    });
  } else if (err instanceof ForeignKeyViolationError) {
    // Handle Error with type ForeignKeyViolationError -> database threw a constraint error
    res.status(409).send({
      message: err.message,
      type: "ForeignKeyViolation",
      data: {
        table: err.table,
        constraint: err.constraint
      }
    });
  } else if (err instanceof CheckViolationError) {
    // Handle Error with type ForeignKeyViolationError -> database threw a check constraint error; not available for MySQL
    res.status(400).send({
      message: err.message,
      type: "CheckViolation",
      data: {
        table: err.table,
        constraint: err.constraint
      }
    });
  } else if (err instanceof DataError) {
    // Handle Error with type DataError -> database threw a invalid data error
    res.status(400).send({
      message: err.message,
      type: "InvalidData",
      data: {}
    });
  } else if (err instanceof DBError) {
    // Handle Error with type DBError -> database threw an error too broad to handle specifically
    res.status(500).send({
      //   message: err.message, // -> modified: It could be possible that the err contains sensitive data
      message: "Unknown Error",
      type: "UnknownDatabaseError",
      data: {}
    });
  } else {
    // Handle every other error generally
    res.status(500).send({
      //   message: err.message, // -> modified: It could be possible that the err contains sensitive data
      message: "Unknown Error",
      type: "UnknownError",
      data: {}
    });
  }
}

module.exports = {
  errorHandler
};
```
In the code above, we check for every possible Objection.js error type, set the response status accordingly (e.g., 404 when no data was found during a find query) and return the message, the error type, and additional data (if possible/ required).

> **Note**
> Our errorHandler function is another middleware, just like Knex.js, Objection.js. Even Express.js is a kind of middleware.
> Middlewares are often used in the context of Express.js framework and are a fundamental concept for Node.js. In a nutshell, it's a function that has access to the request, response, and error objects of your application and does additional stuff on them.

Next step is to include our newly written errorHandler middleware to our project. For this, we have to update our
**server.js** file
```js
const express = require("express");
const app = express();

app.use(express.urlencoded({ extended: false }));
app.use(express.json());

const apiRoutes = require("./routes/api");

const Knex = require("knex");
const knexFile = require("./knexfile.js");
const knex = Knex(knexFile.development);

const { Model } = require("objection");

Model.knex(knex);

app.use("/api", apiRoutes);

// Include error handlers - must be the last one among other middleware or routes to function properly
const { errorHandler } = require("./helpers/error.js");
app.use((err, req, res, next) => {
  errorHandler(err, res);
});

const server = app.listen(8080, error => {
  if (error) {
    console.log("Error running Express");
  }
  console.log("Server is running on port", server.address().port);
});
```
The error-handling middleware in line 22 must be the last among other middleware and routes for it to function correctly.

> **Note**
> Error-handling middleware always takes **four** arguments. You must provide four arguments to identify it as an error-handling middleware function. Even if you donâ€™t need to use the next object, you must specify it to maintain the signature. Otherwise, the next object will be interpreted as regular middleware and will fail to handle errors.
> Look below for an explanation of `next`


#### Use error handler
Now that we created and included our error handling middleware, we are ready to handle errors correctly

**/routes/api/users.js**
```js
// Create endpoint of all users
router.get("/", async (req, res, next) => {
  try {
    const users = await User.query();
    // throw a not found error
    if (!users.length === 0) {
      throw new NotFoundError(users);
    }
    res.json(users);
  } catch (err) {
    next(err);
  }
});

router.post("/", async (req, res, next) => {
  const { name, age } = req.body;

  try {
    const user = await User.query().insert({ name, age });
    res.json(user);
  } catch (err) {
    next(err);
  }
});

// Export to api.js
module.exports = router;
```
In the code above:
- inside the `app.get`, we have added an if statement, which checks if our database query returns rows. If no rows are returned, we do a `throw new NotFoundError(users);`. Throwing an error inside a try block invokes the catch block.
- `next` is an Express.js native function and means to continue to the next matching route and pass our `err` to our error handling middleware (`errorHandler` function). [More information on the next function can be found here](https://expressjs.com/en/guide/using-middleware.html)
- inside the `app.post`, we don't do any custom `        res.status(400).json(err.data);` but let our errorHandler function catch the error type and send a response accordingly.

### Testing the error handler
**Example validation error**
We can invoke a *validation error* inside the `app.post` by simply sending an integer as the name value (without quotation marks).
![WBroKRC.png](https://i.imgur.com/WBroKRC.png)
In the above image, we can see the returned error from our error handler function.

**Example nothing found error**
We can invoke a *not found error* by slightly modifying our `app.get` block not to return any rows.

```js
// Create endpoint of all users
router.get("/", async (req, res, next) => {
  try {
    const users = await User.query().where("name","Penguin Giraf");
    // throw a not found error
    if (!users.length === 0) {
      throw new NotFoundError(users);
    }
    res.json(users);
  } catch (err) {
    next(err);
  }
});
```
We are definitely sure that no name "Penguin Giraf" exists in the database, i.e. the query returns an empty array.

Requesting the URL in Postman displays the error message below
![6RuFKrR.png](https://i.imgur.com/6RuFKrR.png) 

Now our project as an improved and unified error handling, honoring a particular structure.